### ISSUE TITLE
会有web端的支持吗?

### ISSUE THREAD

**Issue by HGladiator** [codeartel/slinote-community#2]
可以docker部署后, 想部署在nas中,   web端 全家人都能用的.  办公家里甚至手机上也都能用同一个,

**Comment by artelcoder** [comment]
书立现在就可以在 web 端访问的，除了 WebDAV 因跨域限制用不了之外，其他功能和客户端一样的。

私有化部署我已列到了路线图里，敬请期待！

**Comment by HGladiator** [comment]
非常棒!,期待
